export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY_BY_CODE = "GET_COUNTRY_BY_CODE";
export const GET_COUNTRIES_ERROR = "GET_COUNTRIES_ERROR";
export const CLEAR_COUNTRY = "CLEAR_COUNTRY";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
